### ISSUE TITLE
dataset.py file not created when installing pathml with pip 

### ISSUE THREAD

**Issue by surya-narayanan** [Dana-Farber-AIOS/pathml#229] opened 2021-11-10 20:47 UTC
Installing pathml with pip only creates hovernet.py and utils.py files in the ml folder. 

**Expected behavior**

Installing pathml with pip also creates dataset.py, to mirror the structure of the github repo.

**Comment by jacobrosenthaldfci** [comment] 2021-11-10 21:14
Hi Surya, so I'm not sure exactly what you mean, but here are some things that might be helpful:

* If you want to modify pathml files, you would usually clone the repo and pip install locally (i.e., `pip install -e .`, as described in the README in installation option 2). If files are not showing up as you expect, you can try git pull to get the latest updates or also check to  make sure you're on the right branch
* If you are talking about installing from PyPI, usually you would just be installing the package into your environment, and not inspecting the source files. But I went ahead and checked the source files that we have uploaded on PyPI and they do include dataset.py (you can check them [here](https://pypi.org/project/pathml/#files))

I hope this helps! If you send more information we might be able to troubleshoot better

**Comment by surya-narayanan** [comment] 2021-11-11 15:44
I am talking about installing from PyPI. When I try importing the TileDataset class from the datasets.py file, in the pathml.ml folder, I am not able to import it. Upon inspection of the directory in which the installed files are housed, I noticed that the datasets.py file is not present. I tried reinstalling pathml using pip, and the issue persisted. 

Please let me know what I should be doing to fix this.

**Comment by jacobrosenthaldfci** [comment] 2021-11-11 16:27
When you do `pip install pathml` it will download the files from PyPI [here](https://pypi.org/project/pathml/#files). You can open the `pathml-1.0.3.tar.gz` file yourself and verify that it does contain dataset.py. 

To double check, I spun up a new pathml environment following the installation instructions in the README and was able to import TileDataset:

![Screen Shot 2021-11-11 at 11 17 47 AM](https://user-images.githubusercontent.com/53529525/141331860-f3868cd4-417d-41c2-9575-1a910dfb3bd4.png)

I am not sure which files you were inspecting, but I followed the steps [here](https://stackoverflow.com/a/47199387) to verify that my installation has the expected files: 

````
(datasettest) jupyter@rosenthal-dxvm:~$ tree /opt/conda/envs/datasettest/lib/python3.8/site-packages/pathml
/opt/conda/envs/datasettest/lib/python3.8/site-packages/pathml
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-38.pyc
│   └── utils.cpython-38.pyc
├── core
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   ├── h5managers.cpython-38.pyc
│   │   ├── masks.cpython-38.pyc
│   │   ├── slide_backends.cpython-38.pyc
│   │   ├── slide_data.cpython-38.pyc
│   │   ├── slide_dataset.cpython-38.pyc
│   │   ├── slide_types.cpython-38.pyc
│   │   ├── tile.cpython-38.pyc
│   │   ├── tiles.cpython-38.pyc
│   │   └── utils.cpython-38.pyc
│   ├── h5managers.py
│   ├── masks.py
│   ├── slide_backends.py
│   ├── slide_data.py
│   ├── slide_dataset.py
│   ├── slide_types.py
│   ├── tile.py
│   ├── tiles.py
│   └── utils.py
├── datasets
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   ├── base_data_module.cpython-38.pyc
│   │   ├── deepfocus.cpython-38.pyc
│   │   ├── pannuke.cpython-38.pyc
│   │   └── utils.cpython-38.pyc
│   ├── base_data_module.py
│   ├── deepfocus.py
│   ├── pannuke.py
│   └── utils.py
├── ml
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   ├── dataset.cpython-38.pyc
│   │   ├── hovernet.cpython-38.pyc
│   │   └── utils.cpython-38.pyc
│   ├── dataset.py
│   ├── hovernet.py
│   └── utils.py
├── preprocessing
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   ├── pipeline.cpython-38.pyc
│   │   ├── tiling.cpython-38.pyc
│   │   └── transforms.cpython-38.pyc
│   ├── pipeline.py
│   ├── tiling.py
│   └── transforms.py
└── utils.py

9 directories, 50 files
````

In order to troubleshoot this further we would probably need a code snippet so that others can reproduce what you are seeing

Thanks!

**Comment by jacobrosenthaldfci** [comment] 2021-11-15 21:20
Closing this because from our conversation it seems to be a local configuration issue, not a bug in pathml. Feel free to reopen if you can reproduce in a fresh environment

**Closed by jacobrosenthaldfci** 2021-11-15 21:20 UTC
Labels: bug
